import { test, expect } from '@playwright/test';
import { docxFixture, pdfFixture, sourceText } from '../tests/document-fixtures';

test('admin uploads Chinese documents; visitor downloads, previews and completes a sourced practice',async({page,browser})=>{
  test.setTimeout(120000);
  await page.goto('/');
  await page.getByRole('button',{name:'知识库',exact:true}).click();
  await page.getByLabel('管理员登录').fill('e2e-test-only-password');
  await page.getByRole('button',{name:'登录',exact:true}).click();
  const word = await docxFixture();
  await page.getByLabel('上传文档').setInputFiles({name:'学习资料.docx',mimeType:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',buffer:word});
  const wordRow=page.locator('.knowledge-list li').filter({hasText:'学习资料.docx'});
  await expect(wordRow.getByRole('button',{name:'用此文档练习'})).toBeEnabled();
  const pdf=pdfFixture();
  await page.getByLabel('上传文档').setInputFiles({name:'中文资料.pdf',mimeType:'application/pdf',buffer:pdf});
  const pdfRow=page.locator('.knowledge-list li').filter({hasText:'中文资料.pdf'});
  await expect(pdfRow.getByRole('button',{name:'用此文档练习'})).toBeEnabled();
  const downloadUrl=(await pdfRow.getByRole('link',{name:'下载原文件'}).getAttribute('href'))!;
  expect(await (await page.request.get(downloadUrl)).body()).toEqual(pdf);
  const wordUrl=(await wordRow.getByRole('link',{name:'下载原文件'}).getAttribute('href'))!;
  expect(await (await page.request.get(wordUrl)).body()).toEqual(word);
  await page.getByRole('button',{name:'退出管理'}).click();
  await expect(page.getByRole('button',{name:'登录',exact:true})).toBeVisible();
  await pdfRow.getByRole('button',{name:'预览文字'}).click();
  await expect(page.getByRole('region',{name:'文档文字预览'})).toContainText('知识管理');
  await pdfRow.getByRole('button',{name:'用此文档练习'}).click();
  await expect(page.locator('.document-selection')).toContainText('中文资料.pdf');
  await page.getByRole('button',{name:'抽取今日关键词'}).click();
  await page.getByRole('button',{name:'准备研究材料'}).click();
  await page.locator('.document-citations summary').click();
  await expect(page.locator('.document-citations')).toContainText('第 1 页');
  await expect(page.locator('.document-citations')).toContainText('知识管理');
  await page.reload();
  await expect(page.locator('.workspace-heading')).toContainText('中文资料.pdf');
  await expect(page.locator('.document-citations')).toContainText('知识管理');
  await page.getByRole('button',{name:'我理解了，准备开讲'}).click();
  await expect(page.locator('.script-paragraph').first()).toContainText('模拟');
  await page.getByRole('button',{name:'开始讲解',exact:true}).click();
  await page.evaluate(()=>{const key='daily-speaking-v1';const saved=JSON.parse(localStorage.getItem(key)!);saved.session.timer.deadline=Date.now()-1;localStorage.setItem(key,JSON.stringify(saved));});
  await page.reload();
  await expect(page.getByText('又多了一点，')).toBeVisible();
  await page.getByRole('button',{name:/练习足迹/}).first().click();
  await expect(page.locator('.history-list')).toContainText('中文资料.pdf');
  await page.getByRole('button',{name:'关闭练习足迹'}).click();

  const visitor=await browser.newContext();
  const visitorPage=await visitor.newPage();await visitorPage.goto('/');
  await visitorPage.getByRole('button',{name:'知识库',exact:true}).click();
  await expect(visitorPage.locator('.knowledge-list')).toContainText('学习资料.docx');
  await expect(visitorPage.getByRole('button',{name:'删除',exact:true})).toHaveCount(0);
  const list=await (await visitor.request.get('/api/documents')).json();
  const id=list.documents.find((d:{name:string})=>d.name==='中文资料.pdf').id;
  expect((await visitor.request.delete(`/api/documents/${id}`,{headers:{Origin:'http://127.0.0.1:3100'}})).status()).toBe(401);
  expect((await visitor.request.post('/api/documents',{headers:{Origin:'http://127.0.0.1:3100'}})).status()).toBe(401);
  await visitor.close();

  await page.getByRole('button',{name:'知识库',exact:true}).click();
  await page.getByLabel('管理员登录').fill('e2e-test-only-password');
  await page.getByRole('button',{name:'登录',exact:true}).click();
  await expect(page.getByLabel('上传文档')).toBeVisible();
  expect((await page.request.delete(`/api/documents/${id}`,{headers:{Origin:'https://foreign.example'}})).status()).toBe(403);
  page.on('dialog',d=>d.accept());
  await pdfRow.getByRole('button',{name:'删除',exact:true}).click();
  await expect(pdfRow).toHaveCount(0);
  expect((await page.request.get(downloadUrl)).status()).toBe(404);
  const missing=await page.request.post('/api/research',{data:{category:'ai',word:'知识管理',documentId:id}});
  expect(missing.status()).toBe(404);
  await page.getByRole('button',{name:'关闭知识库'}).click();
  await page.getByRole('button',{name:'再练一次'}).click();
  await expect(page.locator('.script-paragraph').first()).toBeVisible();
});

test('failed parse preserves original, mobile library fits and login attempts are limited',async({page})=>{
  await page.setViewportSize({width:390,height:844});await page.goto('/');
  await page.getByRole('button',{name:'知识库',exact:true}).click();
  await page.getByLabel('管理员登录').fill('e2e-test-only-password');
  await page.getByRole('button',{name:'登录',exact:true}).click();
  await page.getByLabel('上传文档').setInputFiles({name:'扫描件.pdf',mimeType:'application/pdf',buffer:pdfFixture([''])});
  const row=page.locator('.knowledge-list li').filter({hasText:'扫描件.pdf'});
  await expect(row).toContainText('解析失败');
  await expect(row.getByRole('button',{name:'用此文档练习'})).toBeDisabled();
  await expect(row.getByRole('link',{name:'下载原文件'})).toBeVisible();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  expect(await page.locator('.knowledge-dialog').evaluate(el=>el.scrollWidth<=el.clientWidth)).toBe(true);
  const origin={Origin:'http://127.0.0.1:3100'};
  let status=0;
  for(let i=0;i<6;i++)status=(await page.request.post('/api/admin/session',{headers:origin,data:{password:'wrong'}})).status();
  expect(status).toBe(429);
});
